---
title: "Portfolio Computational Musicology"
author: "Iris Gaarthuis"
date: "2/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
## Computational Musicology

Can I predict film genre, based on the film music playlist of different movies?
In my analysis, I want to identify the measurable traits of the musical scores (different elements) of film music between different genres of movies. I chose this subject, because I thought it would be interesting to identify the different key elements of music used in different genres of movies, because the full emotional effect of a movie is mainly based on the music played (in combination with the visual information). These movies will be romance, comedy, horror and action. From these movie genres, what features contain the most information? For each genre, I’m going to analyze 5-10 movies with their corresponding tracks. Emotions are key elements in these movies. In romance movies, emotions like ‘loving’ en ‘sense of longing’ are the main characteristics, I expect that light tones are key features. In horror movies, fear and anxiety are the main emotions expressed in music. Dark overtones will be present. In action movies, emotions with high intensity like excitement are essential. In comedy movies, ‘happiness’ and ‘joy are the main emotions, so these tracks will contain a lot of musical elements from ‘happy’ music.

Some movies from, for example, a comedy genre, will contain music that will typically belong to an action genre, if there is for example, an exciting scene. So these are atypical tracks that have musical elements from a different genre. That’s why I will look at the mean of the tracks used in a movie.

Timbral, rhythm and pitch will be different across these genres. I will use these fore genre classification. 

Loudness: seen as a relevant musical feature to express emotions (Juslin & Laukka, 2004)
Mode: major vs. minor. 
* happy and tender: mainy major mode. Romantic movies have a lot of these characteristics
* sadness and fear: mainly minor mode.
* anger: even distribution
link between valence and musical mode

## Corpus
Movies from the last decade
Number of movies based on number of tracks
Only Original Motion Picture Soundtrack albums from spotify

Action movies (221 tracks)
1)	Atomic blonde
2)	Baby driver 
3)	Edge of tomorrow
4)	Fast five/furious 7
5)	Hanna
6)	John wick(s)
7)	Kingsman: the secret service
8)	Mad max: fury road
9)	Mission impossible: fallout
10)	Skyfall
11) Avengers: end game

Romantic movies (242 tracks)
1)	Eternal sunshine of the spotless mind
2)	Amélie
3)	Barfi!
4)	La la land
5)	Slumdog millionaire 
6)	Pride & prejudice
7)	About time
8)	The notebook
9)	The fault in our stars
10) Love actually
11) Atonement
12) Silver linings playbook
13) The theory of everything
14) The age of adaline

Horror movies (237 tracks)
1)	Get out
2)	The lighthouse
3)	A quiet place
4)	The conjuring
5)	Upgrade
6)	Split
7)	Hereditary
8)	Doctor sleep
9)	It
---
```
```{r}
library(tidyverse)
```
```{r}
library(spotifyr)
```

```{r}
romantic_movies <- get_playlist_audio_features("","5mlaU10XgmCTkuqxJCX1bk")
horror_movies <- get_playlist_audio_features("", "12aylnVBIgblxtIVgofUiz")
action_movies <- get_playlist_audio_features("", "6Ua5fW3fgV26Vu9b8SxBJA")
```
```{r}
genre <-
  bind_rows(
  romantic_movies %>% mutate(category = "romance"),
  horror_movies %>% mutate(category = "horror"),
  action_movies %>% mutate(category = "action")
  )
```


```{r}
genre %>%
  ggplot(aes(x = valence)) +
  geom_histogram(binwidth = 0.1, fill = "#0c4c8a") +
  facet_wrap(~category) +
  theme_classic()
```
```{r}
genre %>%
  ggplot(aes(x = instrumentalness)) +
  geom_histogram(binwidth = 0.06, fill = "#0c4c8a") +
  facet_wrap(~category) +
  theme_classic()
  
```

```{r}
genre %>%
  ggplot(aes(x = danceability)) +
  geom_histogram(binwidth = 0.05, fill = "#0c4c8a") +
  facet_wrap(~category) +
  theme_classic()
```

```{r}
genre %>%
  ggplot(aes(x = valence, y = energy, color = category)) +
  geom_point(alpha = 0.5) +
  scale_x_log10() +
  theme_bw()
  
```



```{r}
genre %>%
  ggplot(aes(x=valence, fill = category)) +
  geom_histogram(position = "dodge", binwidth = 0.08) +
  theme_classic()
```
```{r}
genre %>%
  ggplot(aes(x = mode, fill = category)) +  # 0 = minor, 1 = major
  geom_bar(position = "dodge") +
  scale_x_continuous(breaks = c(0, 1)) +
  theme_classic()
```
